In [1]:
import numpy as np
import math

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
print(a.ndim)

1


In [4]:
b=np.array([[1,2,3],[4,5,6]])

In [6]:
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
b.ndim

2

In [8]:
b.shape

(2, 3)

In [9]:
a.dtype

dtype('int64')

In [10]:
b.dtype

dtype('int64')

In [12]:
c=np.array([1,2,3,4.5])

In [13]:
c.dtype

dtype('float64')

In [16]:
d=np.ones([2,3])

In [17]:
print(d)

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
e=np.zeros([2,3])

In [19]:
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
#arrange
#starting bound, ending bound, difference between 2 consectutive numbers

In [23]:
f = np.arange(10,30,2)

In [24]:
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [25]:
print(f)

[10 12 14 16 18 20 22 24 26 28]


In [26]:
#linspace 
# starting bound, ending bound, no of items
# generate sequence of floats

In [27]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [28]:
np.linspace(0,2,20)

array([0.        , 0.10526316, 0.21052632, 0.31578947, 0.42105263,
       0.52631579, 0.63157895, 0.73684211, 0.84210526, 0.94736842,
       1.05263158, 1.15789474, 1.26315789, 1.36842105, 1.47368421,
       1.57894737, 1.68421053, 1.78947368, 1.89473684, 2.        ])

In [30]:
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])

c=a-b
d=a*b

print(c)
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [37]:
#arithmetic operation
f=np.array([-10,-15,-30])

c=(f-32)*(5/9)
c

array([-23.33333333, -26.11111111, -34.44444444])

In [38]:
#boolean operation
c>-20

array([False, False, False])

In [40]:
#matrix manipulation

A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])

print(A*B)

[[2 0]
 [0 4]]


In [41]:
#Dot product is done using @
print(A@B)

[[5 4]
 [3 4]]


In [42]:
print(A+B)

[[3 1]
 [3 5]]


In [43]:
#Aggregation Function on Numpy arrays

array1=np.array([[1,2,3],[4,5,6]])
array2=np.array([[7.1,8.2,9.3],[10.4,11.5,12.6]])

array3=array1+array2

In [44]:
print(array3.sum())
print(array3.min())
print(array3.max())
print(array3.mean())

80.1
8.1
18.6
13.35


In [49]:
b=np.arange(1,16,1).reshape(3,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])